language: go
go:
  - 1.7
script: make test build
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ZwgcXhaGUdmsAdVaT+jNjDiofIE7QQ12elRByNbJJZuxcGtVfRGc9aJcL1v0gd+kAuNEjXlwFImgxvgjNkhMC8hJ4xVkEXhxVf8UGWCHfOVmsgtT27OgPc3KkH1M/GbG8hEW3bXitMrpS+Q3JwIJctJSQ/AwAL6uYurldziU8LJNGthLj1XXOtzEihmJ1AQO3w9qCrJXI9YV7KTFndubAnKxaOkqrTDOo8mY88UD/NsoqznR1mYeuPwGotdTY0ltYepeqgQli7R1T5vm2o56L9IW29AmCAsfThVQa4ykREwWGjJtcesBmO0C/5moC6tFZPWniXBM2nFZx4vH5AsmmKUM98zqG9JMsKEoX1nVny1CYu+x5W3QojWEYnUz1jBhZY42+a0rtgL7cnwTqmYcUHJOvALb17c58dNcRZx98d+8X4b2GvPab4ZHsnt3XEWMHDCvi9dVht7MFqPtGvASKxW1GrDML3U30/NZglWuxDFCoGoLYQbU72ndv4qxqm0VZ9DY6s8d9D3NwYe0BCJ38mNi72j4s4O2iZDbwYOw4pqVcF/gqs9gJUZaP14YkTmaIWMAMd5njjFHre5uvdwcNS3M1T6Q8SrzTroPCMBDSZZV9a3q9fueHvupq22MjW2kzJtpNPG98kihAy0Wj/a9zDYdnujHhhMxYN2l5Zr4WO4=
  file: consul-master-election-tagger
  on:
    tags: true
notifications:
  slack:
    secure: eJTF3sFWJQBUEfVjilojsyq169/TuiRBp3Ccd/J2K6j+esJCDdBy5AvdmNZ+15nQFJ0AqWgdsLCyMTZpWGlVCw6+fZGxjlNm8HanqdwYzzjpyZ42HtberApUurJBD/fMRIRbLgJHafENoOSCD2lgKT18vgl0qfFGQIBn3pxx0fxgPlQJsAdLvu8TM1QqMl6HmzOQXFFLYSqz7YeFXPvzee4ZlxejKU/MqZUg34ewoyUTpiaMtktE9U/CeQ8xFX8JRlDCaO1Q3ouOzgjn1arAhp3bOlUasazck1csy95pDeVZ0LYiohKuNikeTXHj+w1oP/YjHi3uGTWY7nfZwiOfcXn7ODW2xuu/1S6ZehAgRGA0cXl0ec6Uu5BCTNA3F/7+sU9xcFT82hmKGGlmDx6uADoQkatBC/81XWUrr1JEsbTDKphGLwwM91uFmjoROnQmbMJxQn+PPfiw5n0HoW1stkS2gsmnFO6PdcFhVVJZD59+9pRVXp9oNxX6U35BLD4Hzpuv6RIO0F8Dpn2wT4K34cHV1iwE73KCJ9GDn8Ik/JS4+fibeoMNNqNmZ5+6MTbl9q3n8O6FhtgEiJGt7nTx6VaY60Xw/3FNXmLYM3WpuKa2zITtp/yZ3qr8oCMjACnu3LGlhcBNbnfsaW3OirpPcPwU7Hz+cFSRa6G3TkHvkws=
